=== thetos7/raytracer-tp/resources/schemas/scene.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "scene_schema",
  "title": "Scene",
  "description": "A raytracing scene",
  "type": "object",
  "properties": {
    "camera": {
      "description": "The scene's camera settings",
      "$ref": "./camera.json"
    },
    "lights": {
      "description": "The scene's light collection",
      "type": "array",
      "items": {
        "$ref": "./light.json"
      }
    },
    "objects": {
      "description": "The scene's object collection",
      "type": "array",
      "items": {
        "$ref": "./object.json"
      }
    },
    "materials": {
      "description": "The scene's material collection",
      "type": "array",
      "items": {
        "$ref": "./material.json"
      }
    }
  },
  "required": ["camera", "lights", "objects", "materials"]
}

=== thetos7/raytracer-tp/Testing/JSON/tex_test2.scene.json
{
  "$schema": "../../resources/schemas/scene.json",
  "materials": [
    {
      "name": "sponge",
      "type": "node",
      "shader": {
        "diffuse_output": "colorRamp.color",
        "nodes": {
          "intersection_info": {
            "type": "intersection_info"
          },
          "voronoi":{
              "type":"voronoi_texture",
              "inputs": {
                "uv": "intersection_info.uv"
              },
              "size": 30
            },
          "voronoi2":{
              "type":"voronoi_texture",
              "inputs": {
                "uv": "intersection_info.uv"
              },
              "size": 20
            },
          "mult":{
            "type":"binary_math",
            "op":"multiplication",
            "inputs": {
              "lhs": "voronoi.factor",
              "rhs": "voronoi2.factor"
            }
          },
          "colorRamp": {
            "type": "color_ramp",
            "inputs": {
              "value": "mult.result"
            },
            "stops": [
              { "value": 0.0, "color": [0.3, 0.3, 0.0] },
              { "value" : 1.0, "color": [1.0, 1.0, 0.0] }
            ]
          }
        }
      }
    }
],
"camera": {
  "position": [
    0.0,
    0.0,
    0.0
  ],
  "focus": [
    2.0,
    0.0,
    0.0
  ],
  "up": [
    0.0,
    0.0,
    1.0
  ],
  "fov": 1.5,
  "aspectRatio": 1.78,
  "zmin": 0.5
},
"lights": [
  {
    "type": "ambientLight",
    "color": [
      1.0,
      1.0,
      1.0
    ]
  }
],
"objects": [
  {
    "type": "triangle",
    "points": [
      [
        2.0,
        -1.0,
        1.0
      ],
      [
        2.0,
        1.0,
        1.0
      ],
      [
        2.0,
        -1.0,
        -1.0
      ]
    ],
    "uvMap": [
      [
        0.0,
        0.0
      ],
      [
        1.0,
        0.0
      ],
      [
        0.0,
        1.0
      ]
    ],
    "material": "double_voronoi"
  },
  {
    "type": "triangle",
    "points": [
      [
        2.0,
        1.0,
        1.0
      ],
      [
        2.0,
        1.0,
        -1.0
      ],
      [
        2.0,
        -1.0,
        -1.0
      ]
    ],
    "uvMap": [
      [
        1.0,
        0.0
      ],
      [
        1.0,
        1.0
      ],
      [
        0.0,
        1.0
      ]
    ],
    "material": "double_voronoi"
  }
]
}

=== thetos7/raytracer-tp/Testing/JSON/scene_view_obj.scene.json
{
    "materials": [
        {
            "name": "lightGrey",
            "type": "uniform",
            "diffuse": [0.8, 0.8, 0.8],
            "specular": 0.0,
            "specularSpread": 1.0,
            "reflectivity": 0.0
        },
        {
            "name": "orange",
            "type": "uniform",
            "diffuse": [1.0, 0.5, 0.1],
            "specular": 0.0,
            "specularSpread": 1.0,
            "reflectivity": 0.0
        }
    ],
    "camera": {
        "position": [0.0, 0.0, -5.0],
        "focus": [0.0, 0.0, 3.0],
        "up": [0.0, -1.0, 0.0],
        "fov" : 1.5,
        "aspectRatio" : 1.78,
        "zmin" : 1.5
    },
    "lights" : [
        {
            "type": "ambientLight",
            "color": [0.15, 0.15, 0.15]
        },
        {
            "type": "pointLight",
            "position": [0.0, -3.0, -5.0],
            "intensity" : [0.8, 0.8, 0.8]
        }
    ],
    "objects" : [
        {
            "type": "mesh_obj",
            "objPath": "../Testing/obj_files/suzanne_tris.obj",
            "center": [0, 0, 0],
            "scale": 1.5,
            "rotate":[180 , 180, -10],
            "material": "orange"

        },
        {
            "type": "plane",
            "reference": [0.0, 0.0, 10.0],
            "normal": [0.0, 0.0, -1.0],
            "material": "lightGrey"
        },
        {
            "type": "plane",
            "reference": [0.0, 4.0, 0.0],
            "normal": [0.0, -1.0, 0.0],
            "material": "lightGrey"
        }
    ]
}

=== thetos7/raytracer-tp/Testing/JSON/tex_test.json
{
  "materials": [
    {
      "name": "procTex",
      "type": "node",
      "shader": {
        "diffuse_output": "colorRamp.color",
        "nodes": {
          "intersectionInfo": { "type": "intersection_info" },
          "colorRamp": {
            "type": "color_ramp",
            "inputs": {
              "value": "amplifiedTex.result"
            },
            "stops": [
              { "value": 0.0, "color": [0.01, 0.69, 0.24] },
              { "value": 0.7, "color": [0.65, 0.35, 0.01] },
              { "value": 0.8, "color": [0.67, 0.67, 0.67] },
              { "value": 1.4, "color": [1.0, 1.0, 1.0] }
            ]
          },
          "voronoiGammaValue": {
            "type": "value",
            "value": 2.0
          },
          "amplitude": {
            "type": "value",
            "value": 1.4
          },
          "noiseGammaValue": {
            "type": "value",
            "value": 4.0
          },
          "voronoiAmplitude": {
            "type": "value",
            "value": 0.9
          },
          "voronoiBias": {
            "type": "value",
            "value": 0.4
          },
          "noiseBias": {
            "type": "value",
            "value": 0.5
          },
          "noiseAmplitude": {
            "type": "value",
            "value": 4.0
          },
          "noiseGamma": {
            "type": "binary_math",
            "inputs": {
              "lhs": "fractalTex.factor",
              "rhs": "noiseGammaValue.value"
            },
            "op": "power"
          },
          "amplifiedNoise": {
            "type": "binary_math",
            "inputs": {
              "lhs": "noiseGamma.result",
              "rhs": "noiseAmplitude.value"
            },
            "op": "multiplication"
          },
          "raisedVoronoi": {
            "type": "binary_math",
            "inputs": {
              "lhs": "adjustedVoronoi.result",
              "rhs": "voronoiBias.value"
            },
            "op": "addition"
          },
          "raisedNoise": {
            "type": "binary_math",
            "inputs": {
              "lhs": "amplifiedNoise.result",
              "rhs": "noiseBias.value"
            },
            "op": "addition"
          },
          "voronoiGamma": {
            "type": "binary_math",
            "inputs": {
              "lhs": "voronoiTex.factor",
              "rhs": "voronoiGammaValue.value"
            },
            "op": "power"
          },
          "adjustedVoronoi": {
            "type": "binary_math",
            "inputs": {
              "lhs": "voronoiGamma.result",
              "rhs": "voronoiAmplitude.value"
            },
            "op": "multiplication"
          },
          "combiner": {
            "type": "binary_math",
            "inputs": {
              "lhs": "raisedVoronoi.result",
              "rhs": "raisedNoise.result"
            },
            "op": "multiplication"
          },
          "amplifiedTex": {
            "type": "binary_math",
            "inputs": {
              "lhs": "combiner.result",
              "rhs": "amplitude.value"
            },
            "op": "multiplication"
          },
          "voronoiTex": {
            "type": "voronoi_texture",
            "inputs": {
              "uv": "intersectionInfo.uv"
            }
          },
          "fractalTex": {
            "type": "fractal_noise_texture",
            "inputs": {
              "uv": "intersectionInfo.uv"
            },
            "scale": 3.0
          }
        }
      }
    }
  ],
  "camera": {
    "position": [0.0, 0.0, 0.0],
    "focus": [2.0, 0.0, 0.0],
    "up": [0.0, 0.0, 1.0],
    "fov": 1.5,
    "aspectRatio": 1.78,
    "zmin": 0.5
  },
  "lights": [
    {
      "type": "ambientLight",
      "color": [1.0, 1.0, 1.0]
    }
  ],
  "objects": [
    {
      "type": "triangle",
      "points": [
        [2.0, -1.0, 1.0],
        [2.0, 1.0, 1.0],
        [2.0, -1.0, -1.0]
      ],
      "uvMap": [
        [0.0, 0.0],
        [1.0, 0.0],
        [0.0, 1.0]
      ],
      "material": "procTex"
    },
    {
      "type": "triangle",
      "points": [
        [2.0, 1.0, 1.0],
        [2.0, 1.0, -1.0],
        [2.0, -1.0, -1.0]
      ],
      "uvMap": [
        [1.0, 0.0],
        [1.0, 1.0],
        [0.0, 1.0]
      ],
      "material": "procTex"
    }
  ]
}

=== thetos7/raytracer-tp/Testing/JSON/demo.scene.json
{
    "$schema": "../../resources/schemas/scene.json",
    "materials": [
        {
            "name": "lightGrey",
            "type": "uniform",
            "diffuse": [0.8, 0.8, 0.8],
            "specular": 0.0,
            "specularSpread": 1.0,
            "reflectivity": 0.0
        },
      {
        "name": "blueShades",
        "type": "node",
        "shader": {
          "diffuse_output": "colorRamp.color",
          "reflectivity_output": "reflectivity.value",
          "nodes": {
            "intersection_info": {
              "type": "intersection_info"
            },
            "reflectivity":{
                "type":"value",
                "value": 0.0
            },
            "noise":{
              "type":"fractal_noise_texture",
              "scale": 8.5,
              "octaves": 10,
              "inputs": {
                "uv": "intersection_info.uv"
              }
            },
            "noise_vec2": {
              "type":"construct_planar",
              "inputs": {
                "x":"noise.factor",
                "y":"noise.factor"
              }
            },
            "voronoi":{
              "type":"voronoi_texture",
              "inputs": {
                "uv": "noise_vec2.result"
              },
              "size": 20
            },
            "wavex":{
              "type":"wave_texture",
              "angle": 0.0,
              "offset": 0.0,
              "scale": 50.0,
              "inputs": {
                "uv": "noise_vec2.result"
              }
            },
            "multiply":{
              "type":"binary_math",
              "op": "multiplication",
              "inputs": {
                "lhs": "voronoi.factor",
                "rhs": "wavex.factor"
              }
            },
            "colorRamp": {
              "type": "color_ramp",
              "inputs": {
                "value": "multiply.result"
              },
              "stops": [
                { "value": 0.0, "color": [0.04, 0.078, 0.262] },
                { "value": 0.5, "color": [0.036, 0.416, 0.285] },
                { "value": 0.777, "color": [0.090, 0.381, 0.500] },
                { "value" : 1.0, "color": [0.043, 0.045, 1.0] }
              ]
            }
          }
        }
      },
      {
        "name": "checkers",
        "type": "node",
        "shader": {
          "diffuse_output": "colorRamp.color",
          "nodes": {
            "intersection_info": {
              "type": "intersection_info"
            },
            "wavex":{
              "type":"wave_texture",
              "angle": 0.0,
              "offset": 0.0,
              "scale": 50.0,
              "inputs": {
                "uv": "intersection_info.uv"
              }
            },
            "wavey":{
              "type":"wave_texture",
              "angle": 1.5707963267948966,
              "offset": 0.0,
              "scale": 50.0,
              "inputs": {
                "uv": "intersection_info.uv"
              }
            },
            "mult":{
              "type":"binary_math",
              "op":"multiplication",
              "inputs": {
                "lhs": "wavey.factor",
                "rhs": "wavex.factor"
              }
            },
            "colorRamp": {
              "type": "color_ramp",
              "inputs": {
                "value": "mult.result"
              },
              "stops": [
                { "value": 0.0, "color": [0.0, 0.0, 0.0] },
                { "value" : 1.0, "color": [1.0, 1.0, 1.0] }
              ]
            }
          }
        }
      },
      {
        "name": "sponge",
        "type": "node",
        "shader": {
          "diffuse_output": "colorRamp.color",
          "specular_output": "mult.result",
          "specular_spread_output": "spread.value",
          "nodes": {
            "intersection_info": {
              "type": "intersection_info"
            },
            "spread":{
                "type":"value",
                "value":1.4
            },
            "voronoi":{
                "type":"voronoi_texture",
                "inputs": {
                  "uv": "intersection_info.uv"
                },
                "size": 30
              },
            "voronoi2":{
                "type":"voronoi_texture",
                "inputs": {
                  "uv": "intersection_info.uv"
                },
                "size": 20
              },
            "mult":{
              "type":"binary_math",
              "op":"multiplication",
              "inputs": {
                "lhs": "voronoi.factor",
                "rhs": "voronoi2.factor"
              }
            },
            "colorRamp": {
              "type": "color_ramp",
              "inputs": {
                "value": "mult.result"
              },
              "stops": [
                { "value": 0.0, "color": [0.3, 0.3, 0.0] },
                { "value" : 1.0, "color": [1.0, 1.0, 0.0] }
              ]
            }
          }
        }
      }
  ],
  "camera": {
      "position": [-7.0, 5.0, 6.0],
      "focus": [4.0, 0.0, 0.0],
      "up": [0.0, 0.0, 1.0],
      "fov" : 1.5,
      "aspectRatio" : 1.78,
      "zmin" : 0.5
  },
  "lights" : [
      {
          "type": "ambientLight",
          "color": [0.15, 0.15, 0.15]
      },
      {
          "type": "pointLight",
          "position": [4.0, 0.0, 10.0],
          "intensity" : [0.8, 0.8, 0.8]
      }
  ],
  "objects" : [
      {
          "type": "mesh_obj",
          "objPath": "../Testing/obj_files/torus_tris.obj",
          "center": [4, 0, 0],
          "scale": 3,
          "rotate":[0 , 0, 90],
          "material": "blueShades"

      },
      {
        "type": "mesh_obj",
        "objPath": "../Testing/obj_files/cube_tris.obj",
        "center": [4, 6, 0],
        "scale": 2.0,
        "rotate":[0 , 0, 0],
        "material": "checkers"

      },
      {
        "type": "mesh_obj",
        "objPath": "../Testing/obj_files/cube_rot_tris.obj",
        "center": [4, -6, 2],
        "scale": 2.0,
        "rotate":[0 , 0, 0],
        "material": "sponge"

      },
      {
          "type": "plane",
          "reference": [20.0, 0.0, 0.0],
          "normal": [-1.0, 0.0, 0.0],
          "material": "lightGrey"
      },
      {
          "type": "plane",
          "reference": [0.0, 0.0, -1.0],
          "normal": [0.0, 0.0, 1.0],
          "material": "lightGrey"
      }
  ]
  }

=== thetos7/raytracer-tp/Testing/JSON/scene1.json
{
    "materials": [
        {
            "name": "lightBlue",
            "type": "uniform",
            "diffuse": [0.5, 0.5, 0.7],
            "specular": [0.0, 0.0, 0.0],
            "specularSpread": 1.0,
            "reflectivity": [0.0, 0.0, 0.0]
        },
        {
            "name": "lightGrey",
            "type": "uniform",
            "diffuse": [0.8, 0.8, 0.8],
            "specular": [0.0, 0.0, 0.0],
            "specularSpread": 1.0,
            "reflectivity": [1.0, 1.0, 1.0]
        },
        {
            "name": "orange",
            "type": "uniform",
            "diffuse": [1.0, 0.5, 0.1],
            "specular": [0.0, 0.0, 0.0],
            "specularSpread": 1.0,
            "reflectivity": [0.0, 0.0, 0.0]
        },
        {
            "name": "red",
            "type": "uniform",
            "diffuse": [0.9, 0.2, 0.2],
            "specular": [0.1, 0.1, 0.1],
            "specularSpread": 0.8,
            "reflectivity": [0.05, 0.05, 0.05]
        }
    ],
    "camera": {
        "position": [0.0, 0.0, 0.0],
        "focus": [4.0, 0.0, 0.0],
        "up": [0.0, 0.0, 1.0],
        "fov" : 1.5,
        "aspectRatio" : 1.78,
        "zmin" : 0.5
    },
    "lights" : [
        {
            "type": "ambientLight",
            "color": [0.15, 0.15, 0.15]
        },
        {
            "type": "pointLight",
            "position": [0.0, 0.0, 3.0],
            "intensity" : [0.8, 0.8, 0.8]
        },
        {
            "type": "sunLight",
            "direction": [0.5, -1, -1],
            "color": [0.8, 0.8, 0.6]
        }
    ],
    "objects" : [
        {
            "type": "plane",
            "reference": [20.0, 0.0, 0.0],
            "normal": [-1.0, 0.0, 0.0],
            "material": "lightBlue"
        },
        {
            "type": "plane",
            "reference": [0.0, 0.0, -1.0],
            "normal": [0.0, 0.0, 1.0],
            "material": "lightGrey"
        },
        {
            "type": "sphere",
            "center": [4.0, -1.0, 1.0],
            "radius": 0.5,
            "material": "orange"
        },
        {
            "type": "triangle",
            "points": [
                [2.0, 1.0, 1.0],
                [2.0, 0.0, 1.0],
                [2.0, 1.0, 0.0]
            ],
            "material": "red"
        }
    ]
}

=== thetos7/raytracer-tp/Testing/JSON/scene_torus.json
{
    "materials": [
        {
            "name": "lightGrey",
            "type": "uniform",
            "diffuse": [0.8, 0.8, 0.8],
            "specular": 0.0,
            "specularSpread": 1.0,
            "reflectivity": 0.0
        },
        {
            "name": "orange",
            "type": "uniform",
            "diffuse": [1.0, 0.5, 0.1],
            "specular": 0.0,
            "specularSpread": 1.0,
            "reflectivity": 0.0
        },
        {
            "name": "terracota_blue",
            "type": "textured",
            "diffuseMap": "../Testing/textures/terracota/diffuse.png",
            "specularMap": "../Testing/textures/terracota/specular.png",
            "specularSpread": 0,
            "reflectivity":0
        }
    ],
    "camera": {
        "position": [0.0, 0.0, 3.0],
        "focus": [4.0, 0.0, 0.0],
        "up": [0.0, 0.0, 1.0],
        "fov" : 1.5,
        "aspectRatio" : 1.78,
        "zmin" : 0.5
    },
    "lights" : [
        {
            "type": "ambientLight",
            "color": [0.15, 0.15, 0.15]
        },
        {
            "type": "pointLight",
            "position": [1.0, 0.0, 4.0],
            "intensity" : [0.8, 0.8, 0.8]
        }
    ],
    "objects" : [
        {
            "type": "mesh_obj",
            "objPath": "../Testing/obj_files/torus_tris.obj",
            "center": [4, 0, 0],
            "scale": 2,
            "rotate":[0 , 0, 90],
            "material": "terracota_blue"

        },
        {
            "type": "plane",
            "reference": [20.0, 0.0, 0.0],
            "normal": [-1.0, 0.0, 0.0],
            "material": "lightGrey"
        },
        {
            "type": "plane",
            "reference": [0.0, 0.0, -1.0],
            "normal": [0.0, 0.0, 1.0],
            "material": "lightGrey"
        }
    ]
}

=== thetos7/raytracer-tp/Testing/JSON/tex_test2.scene_copy.json
{
  "$schema": "../../resources/schemas/scene.json",
  "materials": [
    {
      "name": "procTex",
      "type": "node",
      "shader": {
        "diffuse_output": "colorRamp.color",
        "nodes": {
          "intersection_info": {
            "type": "intersection_info"
          },
          "noise":{
            "type":"fractal_noise_texture",
            "scale": 1.5,
            "octaves": 25,
            "inputs": {
              "uv": "intersection_info.uv"
            }
          },
          "noised_vec2": {
            "type":"construct_planar",
            "inputs": {
              "x":"noise.factor",
              "y":"noise.factor"
            }
          },
          "voronoi":{
            "type":"voronoi_texture",
            "inputs": {
              "uv": "intersection_info.uv"
            },
            "size": 40
          },
          "colorRamp": {
            "type": "color_ramp",
            "inputs": {
              "value": "voronoi.factor"
            },
            "stops": [
              { "value": 0.0, "color": [1.0, 1.0, 1.0] },
              { "value" : 1.0, "color": [0.0, 0.0, 1.0] }
            ]
          }
        }
      }
    }
],
"camera": {
  "position": [
    0.0,
    0.0,
    0.0
  ],
  "focus": [
    2.0,
    0.0,
    0.0
  ],
  "up": [
    0.0,
    0.0,
    1.0
  ],
  "fov": 1.5,
  "aspectRatio": 1.78,
  "zmin": 0.5
},
"lights": [
  {
    "type": "ambientLight",
    "color": [
      1.0,
      1.0,
      1.0
    ]
  }
],
"objects": [
  {
    "type": "triangle",
    "points": [
      [
        2.0,
        -1.0,
        1.0
      ],
      [
        2.0,
        1.0,
        1.0
      ],
      [
        2.0,
        -1.0,
        -1.0
      ]
    ],
    "uvMap": [
      [
        0.0,
        0.0
      ],
      [
        1.0,
        0.0
      ],
      [
        0.0,
        1.0
      ]
    ],
    "material": "procTex"
  },
  {
    "type": "triangle",
    "points": [
      [
        2.0,
        1.0,
        1.0
      ],
      [
        2.0,
        1.0,
        -1.0
      ],
      [
        2.0,
        -1.0,
        -1.0
      ]
    ],
    "uvMap": [
      [
        1.0,
        0.0
      ],
      [
        1.0,
        1.0
      ],
      [
        0.0,
        1.0
      ]
    ],
    "material": "procTex"
  }
]
}
